[package]
name = "cruzfelipee/guiparticleservice"
description = "UI Particle Library focused on ease of use and similarity to the default 3D Particle Emitter"
license = "MIT"
authors = ["cruzfelipee"]
version = "0.1.4"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = [
    ".github",
    ".gitignore",
    ".luaurc",
    "README.md",
    "rokit.toml",
    "selene.toml",
    ]

[dependencies]
