[package]
name = "cruzfelipee/guiparticleservice"
description = "UI Particle Library focused on ease of use and similarity to the default 3D Particle Emitter"
version = "0.2.0"
license = "MIT"
authors = ["cruzfelipee"]
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"
repository = "https://github.com/cruzfelipee/GuiParticleService"
include = [
    "src",
    "LICENSE",
    "wally.toml",
    "default.project.json"
    ]

[dependencies]
