name: Lint

on:
  pull_request:

jobs:
  selene:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up rokit
        run: |
          curl -sSf https://raw.githubusercontent.com/rojo-rbx/rokit/main/scripts/install.sh | bash
          export PATH="$HOME/.rokit/bin:$PATH"
          echo "$HOME/.rokit/bin" >> "$GITHUB_PATH"
          rokit install --no-trust-check

      - name: Lint with Selene
        run: |
          selene src