name: Lint

on:
  pull_request:

jobs:
  selene:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup rokit
        uses: CompeyDev/setup-rokit@v0.1.2

      - name: Lint with Selene
        run: |
          selene src