name: Release To Wally

on:
  push:
    branches:
      - master
    paths:
      - wally.toml

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup rokit
        uses: CompeyDev/setup-rokit@v0.1.2

      - name: Publish to wally
        run: |
          wally login --token "${{ secrets.WALLY_LOGIN_KEY }}"
          wally publish
