name: Style

on:
  pull_request:

jobs:
  stylua:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup rokit
        uses: CompeyDev/setup-rokit@v0.1.2

      - name: Check style with StyLua
        run: |
          stylua --check src